# Generated by Django 4.1 on 2022-12-18 07:03

from django.db import migrations, models
import gwtc.models


class Migration(migrations.Migration):

    dependencies = [
        ("gwtc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to=gwtc.models.get_file_path)),
                ("published_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
